apiVersion: v1
kind: ConfigMap
metadata:
  name: snowflake-id-config
  namespace: snowflake-id
data:
  config.json: |
    {
      "etcd_endpoints": ["myetcd-svc:2379"],
      "etcd_prefix": "/snowflake-id/",
      "etcd_username": "snowflake-id",
      "etcd_password": "passwd",
      "max_server_cnt": 1024
    }