apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-id
  namespace: snowflake-id
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: snowflake-id
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snowflake-id
    spec:
      volumes:
        - name: config
          configMap:
            name: snowflake-id-config
      containers:
        - name: snowflake-id
          image: pengubco/snowflake-id:v0.0.1
          volumeMounts:
            - mountPath: /etc/snowflake-id
              name: config
          args:
            - '-config_from_file=/etc/snowflake-id/config.json'
          ports:
            - containerPort: 7669
            - containerPort: 800

---
apiVersion: v1
kind: Service
metadata:
  name: snowflake-id-svc
  namespace: snowflake-id
spec:
  selector:
    app.kubernetes.io/name: snowflake-id
  type: NodePort
  ports:
    - port: 7669
      targetPort: 7669
      nodePort: 30001
      name: id
    - port: 8001
      targetPort: 8001
      nodePort: 30002
      name: metric