apiVersion: apps/v1
kind: Deployment
metadata:
  name: guiid
  namespace: guiid
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: guiid
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guiid
    spec:
      volumes:
        - name: config
          configMap:
            name: guiid-config
      containers:
        - name: guiid
          image: pengubco/guiid:v0.0.1
          volumeMounts:
            - mountPath: /etc/guiid
              name: config
          args:
            - '-config_from_file=/etc/guiid/config.json'
          ports:
            - containerPort: 7669
            - containerPort: 800

---
apiVersion: v1
kind: Service
metadata:
  name: guiid-svc
  namespace: guiid
spec:
  selector:
    app.kubernetes.io/name: guiid
  type: NodePort
  ports:
    - port: 7669
      targetPort: 7669
      nodePort: 30001
      name: id
    - port: 8001
      targetPort: 8001
      nodePort: 30002
      name: metric
