apiVersion: apps/v1
kind: Deployment
metadata:
  name: i3d
  namespace: i3d
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: i3d
  template:
    metadata:
      labels:
        app.kubernetes.io/name: i3d
    spec:
      volumes:
        - name: config
          configMap:
            name: i3d-config
      containers:
        - name: i3d
          image: pengubco/i3d:v0.0.1
          volumeMounts:
            - mountPath: /etc/i3d
              name: config
          args:
            - '-config_from_file=/etc/i3d/config.json'
          ports:
            - containerPort: 7669
            - containerPort: 800

---
apiVersion: v1
kind: Service
metadata:
  name: i3d-svc
  namespace: i3d
spec:
  selector:
    app.kubernetes.io/name: i3d
  type: NodePort
  ports:
    - port: 7669
      targetPort: 7669
      nodePort: 30001
      name: id
    - port: 8001
      targetPort: 8001
      nodePort: 30002
      name: metric
