apiVersion: v1
kind: Pod
metadata:
  name: myetcd
  labels:
    app.kubernetes.io/name: myetcd
  namespace: guiid
spec:
  containers:
    - name: etcd
      image: bitnami/etcd:latest
      env:
        - name: ETCD_ROOT_PASSWORD
          value: root
      ports:
        - containerPort: 2379
        - containerPort: 2380

---
apiVersion: v1
kind: Service
metadata:
  name: myetcd-svc
  namespace: guiid
spec:
  selector:
    app.kubernetes.io/name: myetcd
  ports:
    - port: 2379
      targetPort: 2379
      name: client
    - port: 2380
      targetPort: 2380
      name: peer
