apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-id
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: snowflake-id
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snowflake-id
    spec:
      containers:
        - name: snowflake-id
          image: pengubco/snowflake-id:v0.0.1
          volumeMounts:
            - mountPath: /etc/snowflake-id
              name: config
          args:
            - '-config_from_file=/etc/snowflake-id/config.json'
          ports:
            - containerPort: 7669
            - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: snowflake-id-svc
spec:
  selector:
    app.kubernetes.io/name: snowflake-id
  type: NodePort
  ports:
    - port: 7669
      targetPort: 7669
      nodePort: 30001
      name: id
    - port: 8001
      targetPort: 8001
      nodePort: 30002
      name: metric

##### begin etcd
---
apiVersion: v1
kind: Pod
metadata:
  name: myetcd
  labels:
    app.kubernetes.io/name: myetcd
spec:
  containers:
    - name: etcd
      image: bitnami/etcd:latest
      env:
        - name: ETCD_ROOT_PASSWORD
          value: root
      ports:
        - containerPort: 2379
        - containerPort: 2380

---
apiVersion: v1
kind: Service
metadata:
  name: myetcd-svc
spec:
  selector:
    app.kubernetes.io/name: myetcd
  ports:
    - port: 2379
      targetPort: 2379
      name: client
    - port: 2380
      targetPort: 2380
      name: peer
##### end etcd

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snowflake-id-config
data:
  config.json: |
    {
      "etcd_endpoints": ["myetcd-svc:2379"],
      "etcd_prefix": "/snowflake-id/",
      "etcd_username": "snowflake-id",
      "etcd_password": "passwd",
      "max_server_cnt": 1024
    }