linters:
  enable:
    - copyloopvar # Checks for loop variable copies in Go 1.22+
    - gofmt
    - goimports
    - gosec
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - tenv # Detects using os.Setenv instead of t.Setenv since Go 1.17
    - unconvert
    - unused
    - govet
    - dupword # Checks for duplicate words in the source code

  nolintlint:
    allow-unused: true

run:
  timeout: 5m